version: 2
project_name: git-attest
builds:
  - main: ./main.go
    binary: git-attest
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - repository:
      owner: SaaSAILabs
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/SaaSAILabs/git-attest"
    description: "A transparency layer for the age of AI-assisted code."
    install: |-
      bin.install "git-attest"
    test: |-
      system "#{bin}/git-attest", "--help"
