# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAttest < Formula
  desc "A transparency layer for the age of AI-assisted code."
  homepage "https://github.com/SaaSAILabs/git-attest"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.1/git-attest_Darwin_x86_64.tar.gz"
      sha256 "3b790a5d7400dee1c6f9cb3ded81a98efeb2be730c0f611c88f63cf0e0d74e9d"

      def install
        bin.install "git-attest"
      end
    end
    on_arm do
      url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.1/git-attest_Darwin_arm64.tar.gz"
      sha256 "4c99f54cbcdf282d789ce92f96397a0408cc39c175654cd7573aad65cae552ec"

      def install
        bin.install "git-attest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.1/git-attest_Linux_x86_64.tar.gz"
        sha256 "d370d4dee068100931b37c86e8115007c3825988dfcaeae40a890dc8b79f4b90"

        def install
          bin.install "git-attest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.1/git-attest_Linux_arm64.tar.gz"
        sha256 "0cadf0908dfaeefd3e81af1c1ce602dc6cd4e0cd79f331a606ce7625b519036d"

        def install
          bin.install "git-attest"
        end
      end
    end
  end

  test do
    system "#{bin}/git-attest", "--help"
  end
end
