# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAttest < Formula
  desc "A transparency layer for the age of AI-assisted code."
  homepage "https://github.com/SaaSAILabs/git-attest"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.0/git-attest_Darwin_x86_64.tar.gz"
      sha256 "e9bce027430d081bbab73d38948a51ac3df6baf8e7a0a22f0b50fb793cd7e84b"

      def install
        bin.install "git-attest"
      end
    end
    on_arm do
      url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.0/git-attest_Darwin_arm64.tar.gz"
      sha256 "4441c3573eca6325772a89a61f604f2ccf93b734c37c53adfcd177fd9043c6f2"

      def install
        bin.install "git-attest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.0/git-attest_Linux_x86_64.tar.gz"
        sha256 "e775d0e799b9151575151080c121729bdbdcd44b1082cbc263374c73a5841453"

        def install
          bin.install "git-attest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SaaSAILabs/git-attest/releases/download/v0.1.0/git-attest_Linux_arm64.tar.gz"
        sha256 "7fc42b47b02d60e5fc2fc5ccaba48f1e0b7d8f60d4e616145f0db7cb78d056a3"

        def install
          bin.install "git-attest"
        end
      end
    end
  end

  test do
    system "#{bin}/git-attest", "--help"
  end
end
